/** @type {import('tailwindcss').Config} */
export default {
  darkMode: 'class',
  content: [
    './index.html',
    './src/**/*.{js,jsx,ts,tsx}',
  ],
  theme: {
    extend: {
      colors: {
        'surface-variant':              '#e2e2e2',
        'inverse-primary':              '#c8c6c5',
        'on-secondary-container':       '#656464',
        'inverse-surface':              '#2f3131',
        'tertiary':                     '#000000',
        'on-primary-fixed-variant':     '#474746',
        'on-secondary-fixed':           '#1b1c1c',
        'secondary':                    '#5f5e5e',
        'on-surface-variant':           '#444748',
        'surface-gray':                 '#F2F2F2',
        'surface-dim':                  '#dadada',
        'secondary-fixed-dim':          '#c8c6c5',
        'on-primary-container':         '#858383',
        'primary-fixed-dim':            '#c8c6c5',
        'on-tertiary-container':        '#459360',
        'surface-container-low':        '#f3f3f4',
        'on-primary-fixed':             '#1c1b1b',
        'error':                        '#ba1a1a',
        'surface-container-high':       '#e8e8e8',
        'on-tertiary':                  '#ffffff',
        'error-container':              '#ffdad6',
        'on-secondary-fixed-variant':   '#474746',
        'outline':                      '#747878',
        'surface':                      '#f9f9f9',
        'on-secondary':                 '#ffffff',
        'inverse-on-surface':           '#f0f1f1',
        'on-tertiary-fixed':            '#00210e',
        'border-light':                 '#E6E6E6',
        'surface-container-highest':    '#e2e2e2',
        'on-primary':                   '#ffffff',
        'on-error':                     '#ffffff',
        'on-error-container':           '#93000a',
        'surface-tint':                 '#5f5e5e',
        'on-background':                '#1a1c1c',
        'primary':                      '#000000',
        'surface-container-lowest':     '#ffffff',
        'on-tertiary-fixed-variant':    '#00522a',
        'background':                   '#f9f9f9',
        'surface-bright':               '#f9f9f9',
        'secondary-container':          '#e4e2e1',
        'surface-container':            '#eeeeee',
        'secondary-fixed':              '#e4e2e1',
        'primary-container':            '#1c1b1b',
        'tertiary-fixed-dim':           '#88d89f',
        'tertiary-container':           '#00210e',
        'tertiary-fixed':               '#a4f4b9',
        'primary-fixed':                '#e5e2e1',
        'on-surface':                   '#1a1c1c',
        'accent-green':                 '#15693B',
        'outline-variant':              '#c4c7c7',
        'text-muted':                   '#6B6B6B',
      },

      borderRadius: {
        DEFAULT: '0.125rem',
        lg:      '0.25rem',
        xl:      '0.5rem',
        full:    '0.75rem',
      },

      spacing: {
        'stack-xl':          '64px',
        'stack-md':          '16px',
        'gutter':            '16px',
        'content-max-width': '720px',
        'stack-lg':          '32px',
        'stack-sm':          '8px',
        'page-margin':       '24px',
      },

      maxWidth: {
        'content-max-width': '720px',
      },

      fontFamily: {
        'label-md':             ['Inter', 'system-ui', 'sans-serif'],
        'display-lg':           ['"Source Serif 4"', 'Georgia', 'serif'],
        'label-sm':             ['Inter', 'system-ui', 'sans-serif'],
        'headline-lg':          ['"Source Serif 4"', 'Georgia', 'serif'],
        'body-lg':              ['"Source Serif 4"', 'Georgia', 'serif'],
        'headline-lg-mobile':   ['"Source Serif 4"', 'Georgia', 'serif'],
        'body-md':              ['"Source Serif 4"', 'Georgia', 'serif'],
        'mono-code':            ['"JetBrains Mono"', 'monospace'],
        // shorthands used in body class
        'serif': ['"Source Serif 4"', 'Georgia', 'serif'],
        'sans':  ['Inter', 'system-ui', 'sans-serif'],
        'mono':  ['"JetBrains Mono"', 'monospace'],
      },

      fontSize: {
        'label-md':           ['14px', { lineHeight: '20px', letterSpacing: '0.02em', fontWeight: '500' }],
        'display-lg':         ['48px', { lineHeight: '56px', letterSpacing: '-0.02em', fontWeight: '700' }],
        'label-sm':           ['12px', { lineHeight: '16px', fontWeight: '400' }],
        'headline-lg':        ['32px', { lineHeight: '40px', letterSpacing: '-0.01em', fontWeight: '700' }],
        'body-lg':            ['20px', { lineHeight: '32px', fontWeight: '400' }],
        'headline-lg-mobile': ['28px', { lineHeight: '34px', fontWeight: '700' }],
        'body-md':            ['18px', { lineHeight: '28px', fontWeight: '400' }],
        'mono-code':          ['14px', { lineHeight: '20px', fontWeight: '400' }],
      },
    },
  },

  plugins: [
    require('@tailwindcss/forms'),
    require('@tailwindcss/container-queries'),
  ],
};
